### ISSUE TITLE
ScreenCaptureEventPlugin.java uses or overrides a deprecated API.

### ISSUE THREAD

**Issue by Tom3652** [nizwar/screen_capture_event#1]
Hello and thanks for the package everything is working as expected :)

I simply would like to point out this warning : 

```
Note: /Users/foxtom/Desktop/flutter/.pub-cache/hosted/pub.dartlang.org/screen_capture_event-1.0.0+1/android/src/main/java/id/nizwar/screen_capture_event/ScreenCaptureEventPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
```

You can see it after a ```flutter clean``` and a rebuild on a real Android device

**Comment by nizwar** [comment]
Thankyou for point out the warning, it was considered as warning and it wont affected your app.
I can't really find what cause this, and i believe some package developer face this also, if you figured out something, PRs are very welcome 😄

**Comment by Tom3652** [comment]
I have actually forked the project to check what it can be and didn't find it either 😅 
I will keep investigating and submit a PR if i find anything
