### ISSUE TITLE
Ios error

### ISSUE THREAD

**Issue by sawproduction** [nizwar/screen_capture_event#9]
Error response from snapshot request action of type 1 gave Error Domain=FBSSceneSnapshotErrorDomain Code=4 "an error occurred during a scene snapshotting operation" UserInfo={NSLocalizedDescription=an error occurred during a scene snapshotting operation, NSLocalizedFailureReason=an unrelated condition or state was not satisfied}

**Comment by nizwar** [comment]
I'm not sure it was related issues with screen_capture_event plugin, i'll close it for now, feel free to open it again with more detail about your issue
